#!/usr/bin/env python3
"""Spec artifact validator and contract helper for the unifable pre-edit gate.

Thin facade: the implementation lives in focused sub-modules and is re-exported here
so existing callers (`from spec import X` / `import spec as spec_mod; spec_mod.X`) and
the `spec.py <cmd>` CLI keep working unchanged. New production code should import from
the real module instead:

  - spec_schema          schema, fake-evidence markers, citation-format helpers
  - spec_io              session/project resolution + spec.json read/write
  - spec_validation      validate_spec + prior-art waiver rules
  - spec_contracts       per-grade contract strings + validation block text
  - spec_tasks           task model (CRUD, status, dedup, supersession)
  - spec_judge           judge prompts/schemas + judge_* structured calls
  - spec_stop_validate   Stop-path: run checks, adjudicate, heal, finalize
  - spec_cli             argv dispatch + `unifable` subcommands

State is one spec.json per (canonical project root, session), so a new session never
inherits a prior one's spec and two repos sharing a session id do not collide.
"""

from __future__ import annotations

try:  # bare import when scripts/gate is on sys.path (hooks + tests); package import otherwise
    # notify_spec_update is defined in model_notify but historically re-exported here
    # (tests patch `spec.notify_spec_update`); keep the binding for back-compat.
    from model_notify import format_spec_status, notify_spec_update  # noqa: F401
    from spec_cli import (  # noqa: F401
        _apply_cli_context,
        _cmd_add_frontier,
        _cmd_add_task,
        _cmd_contract,
        _cmd_dispute,
        _cmd_doctor,
        _cmd_doctor_session_env,
        _cmd_restate,
        _cmd_set_primary,
        main,
    )
    from spec_contracts import (  # noqa: F401
        _CONTRACT,
        contract_string,
        format_spec_validation_block,
    )
    from spec_io import (  # noqa: F401
        _CANONICAL_ROOT_CACHE,
        _PROJECT_MARKERS,
        _SAFE_KEY_RE,
        _find_fragmented_specs,
        _git_toplevel,
        _read_spec_file,
        _relocate_spec,
        _safe_session,
        _seed_goal,
        _spec_file_substantive,
        canonical_project_root,
        dir_hash,
        ensure_spec_scaffold,
        format_spec_location,
        load_spec,
        resolve_session_id,
        resolve_session_id_with_source,
        save_spec,
        session_dir,
        spec_path,
    )
    from spec_judge import (  # noqa: F401
        _ADJUST_REQ_SCHEMA,
        _COMPARISON_SCHEMA,
        _COMPARISON_SYSTEM,
        _DISCOVER_SCHEMA,
        _DISCOVER_SYSTEM,
        _DISPUTE_ADJUDICATION,
        _DISPUTE_OBSOLETE_RULE,
        _DISPUTE_SCHEMA,
        _FRONTIER_JUDGE_SCHEMA,
        _FRONTIER_JUDGE_SYSTEM,
        _HINT_MAX,
        _HINT_PLACEHOLDERS,
        _HINT_SCHEMA,
        _JUDGE_CORE_GUIDANCE,
        _JUDGE_FEEDBACK_GUIDANCE,
        _JUDGE_HEAL_REASON_BRITTLE,
        _JUDGE_HEAL_SCHEMA,
        _JUDGE_HEAL_SYSTEM,
        _JUDGE_SCHEMA,
        _JUDGE_SYSTEM,
        _JUDGE_TRANSCRIPT_SECTION,
        _NEW_REQ_SCHEMA,
        _PLAN_MODE_JUDGE_RULES,
        _PRIMARY_JUDGE_SYSTEM,
        _TASK_VERDICT_ITEM_SCHEMA,
        _VALIDATE_ALL_SCHEMA,
        _VALIDATE_ALL_SYSTEM,
        _apply_adjustments,
        _build_validate_all_user,
        _evidence_payload,
        _judge_context,
        _judge_owned_open_tasks,
        _judge_result,
        _judge_schema_for_task,
        _judge_system_for_task,
        _judge_system_with_transcript,
        _judge_user,
        _normalize_adjustments,
        _normalize_hint,
        _normalize_new_requirements,
        _normalize_scope_paths,
        _plan_mode_judge_section,
        _render_judge_transcript,
        _session_context_payload,
        _validate_all_system,
        judge_all_tasks,
        judge_discover_frontiers,
        judge_dispute,
        judge_frontier_comparison,
        judge_heal_own_requirements,
        judge_hint,
        judge_task,
        judge_tasks,
    )
    from spec_schema import (  # noqa: F401
        _PATH_LINE_RE,
        _URL_RE,
        FAKE_MARKERS,
        GRADES,
        SPEC_SCHEMA,
        check_fake_evidence,
        is_path_line,
        is_source_url,
        prior_art_parts,
        repo_context_of,
        repo_context_parts,
        spec_template,
    )
    from spec_stop_validate import (  # noqa: F401
        _CHECK_BUILTINS,
        _CHECK_TIMEOUT,
        _ENV_ASSIGN_RE,
        _FILE_EXT_RE,
        _OUTPUT_LIMIT,
        _STRUCTURE_OPS,
        _apply_check_result,
        _apply_dispute,
        _apply_dispute_verdict,
        _apply_runnable_check_result,
        _check_inputs_for_task,
        _check_parallelism,
        _collect_stop_validate_item,
        _has_shell_structure,
        _prior_exit_for_failed_task,
        _run_stop_checks_parallel,
        _should_replay_failed_check,
        _validate_one_task,
        auto_validate_spec,
        deterministic_heal_judge_requirements,
        heal_judge_owned_requirements,
        is_runnable_check,
        run_check,
    )
    from spec_tasks import (  # noqa: F401
        _PURPOSE_DEDUP_MIN_CONTAINMENT,
        _PURPOSE_DEDUP_MIN_LEN,
        _SEMVER_LITERAL_RE,
        _TITLE_PARENS_RE,
        _VERSION_PIN_CONTEXT_RE,
        JUDGE_MAX_UNRESOLVED_ADDED,
        RESOLVED_STATUSES,
        _apply_supersedes_bundle,
        _current_requirements_payload,
        _filter_judge_new_requirements,
        _is_heavy_spec,
        _new_task,
        _next_task_id,
        _norm_title_conflicts,
        _normalize_title,
        _task_is_pending,
        _titles_purpose_duplicate,
        all_tasks_validated,
        append_frontier_task,
        detect_requirement_fragmentation,
        find_task,
        is_brittle_version_pinned_requirement,
        set_primary_task,
    )
    from spec_validation import (  # noqa: F401
        _EXTERNAL_RESEARCH_RE,
        _IN_REPO_WORK_RE,
        _REPO_MAINTENANCE_RE,
        repo_maintenance_waives_prior_art,
        validate_spec,
    )
except ImportError:  # pragma: no cover
    from scripts.gate.model_notify import format_spec_status, notify_spec_update  # noqa: F401
    from scripts.gate.spec_cli import (  # noqa: F401
        _apply_cli_context,
        _cmd_add_frontier,
        _cmd_add_task,
        _cmd_contract,
        _cmd_dispute,
        _cmd_doctor,
        _cmd_doctor_session_env,
        _cmd_restate,
        _cmd_set_primary,
        main,
    )
    from scripts.gate.spec_contracts import (  # noqa: F401
        _CONTRACT,
        contract_string,
        format_spec_validation_block,
    )
    from scripts.gate.spec_io import (  # noqa: F401
        _CANONICAL_ROOT_CACHE,
        _PROJECT_MARKERS,
        _SAFE_KEY_RE,
        _find_fragmented_specs,
        _git_toplevel,
        _read_spec_file,
        _relocate_spec,
        _safe_session,
        _seed_goal,
        _spec_file_substantive,
        canonical_project_root,
        dir_hash,
        ensure_spec_scaffold,
        format_spec_location,
        load_spec,
        resolve_session_id,
        resolve_session_id_with_source,
        save_spec,
        session_dir,
        spec_path,
    )
    from scripts.gate.spec_judge import (  # noqa: F401
        _ADJUST_REQ_SCHEMA,
        _COMPARISON_SCHEMA,
        _COMPARISON_SYSTEM,
        _DISCOVER_SCHEMA,
        _DISCOVER_SYSTEM,
        _DISPUTE_ADJUDICATION,
        _DISPUTE_OBSOLETE_RULE,
        _DISPUTE_SCHEMA,
        _FRONTIER_JUDGE_SCHEMA,
        _FRONTIER_JUDGE_SYSTEM,
        _HINT_MAX,
        _HINT_PLACEHOLDERS,
        _HINT_SCHEMA,
        _JUDGE_CORE_GUIDANCE,
        _JUDGE_FEEDBACK_GUIDANCE,
        _JUDGE_HEAL_REASON_BRITTLE,
        _JUDGE_HEAL_SCHEMA,
        _JUDGE_HEAL_SYSTEM,
        _JUDGE_SCHEMA,
        _JUDGE_SYSTEM,
        _JUDGE_TRANSCRIPT_SECTION,
        _NEW_REQ_SCHEMA,
        _PLAN_MODE_JUDGE_RULES,
        _PRIMARY_JUDGE_SYSTEM,
        _TASK_VERDICT_ITEM_SCHEMA,
        _VALIDATE_ALL_SCHEMA,
        _VALIDATE_ALL_SYSTEM,
        _apply_adjustments,
        _build_validate_all_user,
        _evidence_payload,
        _judge_context,
        _judge_owned_open_tasks,
        _judge_result,
        _judge_schema_for_task,
        _judge_system_for_task,
        _judge_system_with_transcript,
        _judge_user,
        _normalize_adjustments,
        _normalize_hint,
        _normalize_new_requirements,
        _normalize_scope_paths,
        _plan_mode_judge_section,
        _render_judge_transcript,
        _session_context_payload,
        _validate_all_system,
        judge_all_tasks,
        judge_discover_frontiers,
        judge_dispute,
        judge_frontier_comparison,
        judge_heal_own_requirements,
        judge_hint,
        judge_task,
        judge_tasks,
    )
    from scripts.gate.spec_schema import (  # noqa: F401
        _PATH_LINE_RE,
        _URL_RE,
        FAKE_MARKERS,
        GRADES,
        SPEC_SCHEMA,
        check_fake_evidence,
        is_path_line,
        is_source_url,
        prior_art_parts,
        repo_context_of,
        repo_context_parts,
        spec_template,
    )
    from scripts.gate.spec_stop_validate import (  # noqa: F401
        _CHECK_BUILTINS,
        _CHECK_TIMEOUT,
        _ENV_ASSIGN_RE,
        _FILE_EXT_RE,
        _OUTPUT_LIMIT,
        _STRUCTURE_OPS,
        _apply_check_result,
        _apply_dispute,
        _apply_dispute_verdict,
        _apply_runnable_check_result,
        _check_inputs_for_task,
        _check_parallelism,
        _collect_stop_validate_item,
        _has_shell_structure,
        _prior_exit_for_failed_task,
        _run_stop_checks_parallel,
        _should_replay_failed_check,
        _validate_one_task,
        auto_validate_spec,
        deterministic_heal_judge_requirements,
        heal_judge_owned_requirements,
        is_runnable_check,
        run_check,
    )
    from scripts.gate.spec_tasks import (  # noqa: F401
        _PURPOSE_DEDUP_MIN_CONTAINMENT,
        _PURPOSE_DEDUP_MIN_LEN,
        _SEMVER_LITERAL_RE,
        _TITLE_PARENS_RE,
        _VERSION_PIN_CONTEXT_RE,
        JUDGE_MAX_UNRESOLVED_ADDED,
        RESOLVED_STATUSES,
        _apply_supersedes_bundle,
        _current_requirements_payload,
        _filter_judge_new_requirements,
        _is_heavy_spec,
        _new_task,
        _next_task_id,
        _norm_title_conflicts,
        _normalize_title,
        _task_is_pending,
        _titles_purpose_duplicate,
        all_tasks_validated,
        append_frontier_task,
        detect_requirement_fragmentation,
        find_task,
        is_brittle_version_pinned_requirement,
        set_primary_task,
    )
    from scripts.gate.spec_validation import (  # noqa: F401
        _EXTERNAL_RESEARCH_RE,
        _IN_REPO_WORK_RE,
        _REPO_MAINTENANCE_RE,
        repo_maintenance_waives_prior_art,
        validate_spec,
    )


if __name__ == "__main__":
    raise SystemExit(main())
